Django-Online_shop1/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Django-Online_shop1/django_online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', include('shop.urls', namespace='shop')),
                   
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Online_shop1/online_shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', include('shop.urls', namespace='shop')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Online_shop1/shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
   
    path('', views.home, name='home'),
    path('category/<slug:slug>/', views.home, name='category_filter'),
    path('search/', views.search, name='search_products'),
    path('search/', views.search, name='search'),  # Add this line
    path('<slug:slug>/', views.product_detail, name='product_detail'),  # Keep this last to avoid conflicts
]
    

Django-Online_shop1/shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='sub_categories', null=True,
                                     blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolut_url(self):
        return reverse('shop:category_filter', args={self.slug})


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%b/%d/')
    description = models.TextField()
    price = models.IntegerField()
    status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolut_url(self):
        return reverse('shop:product_detail', args={self.slug, })




    # def get_absolute_url(self):
    #     return reverse('product_detail', kwargs={'slug': self.slug})

Django-Online_shop1/shop/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from cart.forms import Add2CartForm
from shop.models import Product, Category


def home(request, slug=None):
    products = Product.objects.filter(status=True)
    categories = Category.objects.filter(is_sub=False)
   
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = products.filter(category=category)
    return render(request, 'shop/home.html', {'products': products, 'categories': categories})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    form = Add2CartForm()
    return render(request, 'shop/product_detail.html', {'product': product, 'form': form})


def search(request):
    query = request.GET.get('q', '').strip()
    if not query:
        return render(request, 'shop/search_results.html', {'products': [], 'query': query})
    
    products = Product.objects.filter(name__icontains=query)
    context = {'products': products, 'query': query}
    return render(request, 'shop/search_results.html', context)

Django-Online_shop1/shop/templates/shop/home.html
{% extends 'base.html' %}

{% comment %} {% extends 'base.html' %}
{% load thumbnail %}

{% block title-head %}
 | Store |
{% endblock %}

{% block lead %}  {% endcomment %}
    {% comment %} this project made with Django 💎 ❤️ Home PAGE {% endcomment %}


    {% comment %} {% endblock %}

{% block content %} {% endcomment %}
  


{% comment %} {% for category in categories %}
        <div class="btn-group">
            <a href="{{ category.get_absolut_url }}" class="btn btn-danger">{{ category.name }}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
                    aria-expanded="false">

            </button>
            <ul class="dropdown-menu">
                {% for sub in category.sub_categories.all %}
                    <li><a class="dropdown-item" href="{{ sub.get_absolut_url }}">{{ sub.name }}</a></li>
                {% endfor %}

            </ul>
        </div>
    {% endfor %} {% endcomment %}
    
    
    {% comment %} <br><br>
    <br><br> 
    {% for product in products %}
        <div class="card" style="width: 20rem; height: 25rem; display: inline-block;  margin: 30px; vertical-align: top;" >
            {% thumbnail product.image "200x200" as img %}
            
                <img src="{{ img.url }}" class="card-img-op" alt="...">
            {% endthumbnail %}
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description|truncatewords:5 }}</p>
                <a href="{{ product.get_absolut_url }}" class="btn btn-primary">show detail</a>
            </div>
        </div>
    {% endfor %}

{% endblock %}  {% endcomment %}


{% comment %} ================================== {% endcomment %}

{% load thumbnail %}
{% load static %}

{% block extra_css %}

{% endblock %}

{% block title-head %}
    | Store |
{% endblock %}

{% block content %} 
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<!-- Navbar -->
{% comment %} {% include 'layouts/navbar.html'%} {% endcomment %}

<!-- Categories Section -->
{% comment %} <section class="categories" style="text-align: center; margin: 20px 0;">
    <h2>Shop by Categories</h2>
     <ul class="categories" style="justify-content: center;">
        <li><a href="/category/Electronics/" class="btn btn-primary">Electronics</a></li>
        <li><a href="/category/clothes/" class="btn btn-primary">Electronics & Gaming</a></li>
    </ul> 
</section> {% endcomment %}





<!-- Product Cards -->
 

<section class="cards-container">
    {% for product in products %}
        <div class="card">
            <img src="{{ product.image.url }}" alt="{{ product.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description|truncatewords:5 }}</p>
                <a href="{{ product.get_absolut_url }}" class="btn-primary">Show Detail</a>

                
            </div>
        </div>
    {% empty %}
        <p>No products available.</p>
    {% endfor %}
</section>





{% endblock %}

Django-Online_shop1/shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% comment %} {% extends 'base.html' %}



{% block content %}
    <h3>{{ product.name }}</h3>
    <small>{{ product.created }}</small>
    <p>{{ product.price }} $</p>
    <img src="{{ product.image.url }}" width="200px" height="200px" alt="{{ product.name }}">
    <hr/>
    <p>{{ product.description }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-primary" value="Add to cart">
       
    </form>
{% endblock %} {% endcomment %}


{% load static %}

{% block content %}


<link rel="stylesheet" href="{% static 'css/product_detail.css' %}">

<div class="cart-container">
    <div class="cart-card">
        <div class="cart-card-header">
            <span>{{ product.name }}</span>
        </div>
        <div class="cart-card-body">
            <img src="{{ product.image.url }}" alt="{{ product.name }}" style="width: 100%; border-radius: 10px; margin-bottom: 15px;">
            <p class="cart-card-text">Created on: {{ product.created }}</p>
            <p class="cart-card-title">${{ product.price }}</p>
            <p class="cart-card-text">{{ product.description }}</p>
            <form action="{% url 'cart:cart_add' product.id %}" method="post" style="margin-top: 20px;">
                {% csrf_token %}
                {{ form }}
                <input type="submit" class="btn btn-primary" value="Add to cart">
            </form>
        </div>
    </div>
</div>
{% endblock %}

Django-Online_shop1/shop/templates/shop/search_results.html
{% extends 'base.html' %}
{% load thumbnail %}
{% comment %} {% block content %}
<h2>Search Results for "{{ query }}"</h2>

<div class="product-container">
    {% for product in products %}
        <div class="card">
            <img src="{{ product.image.url }}" alt="{{ product.name }}">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <h5 class="card-title"> {{ product.name|cut:query|safe }}<strong style="color: #f9a825;">{{ query }}</strong></h5>
                <p class="card-text">{{ product.description|truncatewords:10 }}</p>
                <a href="{{ product.get_absolute_url }}" class="btn-primary">View Details</a>
                 <h5 class="card-title">
                    {{ product.name|cut:query|safe }}<strong style="color: #f9a825;">{{ query }}</strong>
                </h5>
                
             </div>
        </div>
    {% empty %}
        <p>No products found matching your search query.</p>
    {% endfor %}
</div>
{% endblock %}  {% endcomment %}

{% load static %}

{% block content %}


<link rel="stylesheet" href="{% static 'css/search_page.css' %}">


<h2>Search Results for "{{ query }}"</h2>

<div class="product-container">
    {% for product in products %}
        <div class="card">
            {% if product.image %}
             
            <img src="{{ product.image.url }}" alt="{{ product.name }}" style="width: 250px; height: 300px; object-fit: cover;">

            
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description|truncatewords:10 }}</p>
                <a href="{{ product.get_absolut_url }}" class="btn-primary">View Details</a>
            </div>
        </div>
    {% empty %}
        <p>No products found matching your search query.</p>
    {% endfor %}
</div>
{% endblock %}