Django-Online_shop1/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Django-Online_shop1/django_online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', include('shop.urls', namespace='shop')),
                   
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Online_shop1/online_shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', include('shop.urls', namespace='shop')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Online_shop1/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('<int:order_id>/', views.detail, name='detail'),
    path('payment/<int:order_id>/<int:price>', views.payment, name='payment'),
    path('verify/', views.verify, name='verify'),
    path('apple-coupon/<int:order_id>', views.coupon_apply, name='coupon_apply'),
]

Django-Online_shop1/cart/models.py
from django.db import models

# Create your models here.

Django-Online_shop1/cart/forms.py
from django import forms


class Add2CartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9, widget=forms.NumberInput(attrs={'class': 'form-control','placeholder': 'quantity'}))

Django-Online_shop1/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from cart.forms import Add2CartForm
from shop.models import Product
from cart.utils.cart import Cart
from django.views.decorators.http import require_POST
from django.contrib import messages
from cart.notification import Notification  

def detail(request):
    cart = Cart(request)
    notification = Notification()  
    cart.add_observer(notification)  
    notification.update(cart) 
    # return render(request, template_name='cart/detail.html', context={'cart': cart})
    return render(request, template_name='cart/detail.html', context={'cart': cart, 'notifications': notification.messages})

   


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = Add2CartForm(request.POST)  
    if form.is_valid():
        data = form.cleaned_data
        cart.add(product=product, quantity=data['quantity'])
    return redirect('cart:detail')
    


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

Django-Online_shop1/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% comment %} {% extends 'base.html' %}


{% block title %}
    cart
{% endblock %}

{% block title-head %}
    Your Own Cart
{% endblock %}

{% block content %}
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Total Price</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}

            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
                <td>
                    <a href="{% url 'cart:cart_remove' item.product.id %}" class="btn btn-warning">remove</a>
                </td>
            </tr>

        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="4"></td>
            <td>{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
{% endblock %} {% endcomment %}

{% load static %}


{% block title %}
    Cart
{% endblock %}

{% block title-head %}
    Your Own Cart
{% endblock %}

{% block content %}



<link rel="stylesheet" href="{% static 'css/cart.css' %}">

<div class="cart-container">


    {% if notifications %}
        <div class="alert alert-info">
            <ul>
                {% for notification in notifications %}
                 <h2></h2>
                    <li>{{ notification }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}


    {% for item in cart %}
        <div class="cart-card">
            <div class="cart-card-body">
                
                <h5 class="cart-card-title">{{ item.product }}</h5>
                <p class="cart-card-text">Quantity: {{ item.quantity }}</p>
                <p class="cart-card-text">Unit Price: ${{ item.price }}</p>
                <p class="cart-card-text">Total Price: ${{ item.total_price }}</p>
                <a href="{% url 'cart:cart_remove' item.product.id %}" class="btn btn-warning">Remove</a>
            </div>
        </div>
    {% endfor %}
    <div class="cart-summary">
        <h3>Total Price: ${{ cart.get_total_price }}</h3>
        <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
    </div>
</div>
{% endblock %}